### ISSUE TITLE
spotify and chrome don't seem to show up in the plugin

### ISSUE THREAD

**Issue by ask-compu** [mirobouma/MusicControl#1]
playing any kind of content in both spotify (flatpak) and google chrome (flatpak) doesn't show up in this plugin, the plugin show no available players

**Comment by mirobouma** [comment]
Hm both Spotify and Chrome show up correctly in the media controls for me. Please make sure you run the flatpaks through game mode (they should show up only if they are running or in the background) and are running on the latest decky version (v2.0.5-pre13).

If this doesn't work, can you try running `printenv | grep DBUS_SESSION_BUS_ADDRESS` in your console and verify that its set to `unix:path=/run/user/1000/bus`?

**Comment by ask-compu** [comment]
yes they're running through game mode, should i do the print thing in game mode?

**Comment by mirobouma** [comment]
ideally if you can yes (you can use PuTTY to ssh in and execute the command there

**Comment by ask-compu** [comment]
```
(deck@steamdeck ~)$ printenv | grep DBUS_SESSION_BUS_ADDRESS
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```

**Comment by mirobouma** [comment]
Hmm everything looks correct, so it should work... do you have discord? would be easier to help debugging. If so please join https://discord.gg/ZU74G2NJzk and in #support-plugins talk to me in the MusicControl Support thread

**Comment by ask-compu** [comment]
![image](https://user-images.githubusercontent.com/11810555/185476147-1f9c9136-a631-406a-adaf-451eff1a1c44.png)

**Comment by mirobouma** [comment]
While having spotify open in game mode, running the following command:
```dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames```
should show org.mpris.MediaPlayer2.spotify.. is that the case?
![image](https://user-images.githubusercontent.com/5081269/185476893-00a1bb1b-b0f1-48a7-a0bd-4de6a217beab.png)

**Comment by mirobouma** [comment]
Also in the case that you are running on the preview steam deck branch, install version 1.0.2 of MusicControl from the decky plugin store and reboot to see if this has any effect

**Comment by ask-compu** [comment]
> Also in the case that you are running on the preview steam deck branch, install version 1.0.2 of MusicControl from the decky plugin store and reboot to see if this has any effect

i am not on the preview branch, i'm on the default stable branch, and i'm already running version 1.0.2, should i be running a different version?

**Comment by ask-compu** [comment]
> While having spotify open in game mode, running the following command: `dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames` should show org.mpris.MediaPlayer2.spotify.. is that the case? ![image](https://user-images.githubusercontent.com/5081269/185476893-00a1bb1b-b0f1-48a7-a0bd-4de6a217beab.png)

```
(1)(deck@steamdeck ~)$ dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1660853998.897871 sender=org.freedesktop.DBus -> destination=:1.1139 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.1093"
      string "org.kio5.kio_http_cache_cleaner"
      string "org.freedesktop.portal.IBus"
      string "org.freedesktop.ReserveDevice1.Audio0"
      string "org.freedesktop.portal.Desktop"
      string "org.freedesktop.ReserveDevice1.Audio1"
      string "com.feralinteractive.GameMode"
      string ":1.945"
      string "org.a11y.Bus"
      string "org.freedesktop.systemd1"
      string ":1.64"
      string ":1.1121"
      string "org.freedesktop.impl.portal.PermissionStore"
      string ":1.65"
      string ":1.1133"
      string ":1.1122"
      string ":1.11"
      string ":1.66"
      string ":1.1134"
      string "org.mpris.MediaPlayer2.spotify"
      string ":1.67"
      string ":1.1135"
      string ":1.0"
      string "org.freedesktop.Flatpak"
      string ":1.1136"
      string ":1.1"
      string "org.pulseaudio.Server"
      string ":1.1137"
      string ":1.1138"
      string ":1.1127"
      string ":1.3"
      string ":1.1139"
      string ":1.4"
      string "org.freedesktop.impl.portal.desktop.kde"                                                                            
      string ":1.1091"                                                                                                            
      string ":1.5"
      string "ca.desrt.dconf"
      string "org.freedesktop.portal.Documents"
      string ":1.1092"
      string "org.freedesktop.IBus"
      string ":1.149"
   ]

```

yep it's there

**Comment by mirobouma** [comment]
Issue was fixed by rebooting the steam deck, closing the issue, feel free to reopen if the problem reoccurs (but most likely will be a decky loader issue if that happens)

**Comment by ask-compu** [comment]
seems a reboot of the steam deck fixed it somehow
