### ISSUE TITLE
[Suggestion] D-Bus Operability Enhancement

### ISSUE THREAD

**Issue by OdinVex** [mirobouma/MusicControl#4]
Not all user IDs are the same, some people have begun to add other user accounts (they have different IDs). Perhaps updating code to reflect the correct ID dynamically instead of assuming 1000 might be best.

**Comment by mirobouma** [comment]
Yeah I was thinking of that possibility, I will keep it in mind for a future release.

**Comment by mirobouma** [comment]
Super late, but 1.1.3 will include this change when merged: 
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/261
Closing the ticket
