### ISSUE TITLE
No support for nuclear-js

### ISSUE THREAD

**Issue by Lutitious** [mirobouma/MusicControl#5]
I tested nuclear-js with this plugin but it does not seem to work correctly

**Comment by mirobouma** [comment]
Support for all apps are not guaranteed, Nuclear-js probably does not properly implement the MPRIS dbus interface. Unfortunately support for nuclear-js is out of scope for me to support.

**Comment by Lutitious** [comment]
So it turns out nuclear flatpak doesnt have support for MPRIS, but the appimage does so using that works
